
from core.llm import call_llm, load_skill
from core.logger import get_logger
from core.output_export import export_agent_output

logger = get_logger("struct")

_SKILL = load_skill("agents/structuring/SKILLS.md")


def run(state):
    user = f"Idea: {state['input']}\nAnswers: {state['answers']}"
    
    if state.get("is_synthetic_answers"):
        logger.warning("Answers are synthetic. Adding warning to prompt.")
        user += "\n\n[WARNING: The interview answers provided above were auto-generated by an AI simulating a stakeholder. Treat them as plausible assumptions rather than verified ground truth. If they conflict logically, rely on best practices.]"

    uc = call_llm(user, system=_SKILL)

    export_agent_output(
        "struct",
        output={"usecase": uc},
        metadata={
            "iteration": state.get("iterations", 0),
            "is_synthetic_answers": state.get("is_synthetic_answers", False),
        },
    )

    return {**state, "usecase": uc}
