import json
import os
import re
from typing import Tuple

from core.llm import call_llm, load_skill
from core.logger import get_logger
from core.output_export import export_agent_output
from core.kg_client import load_graph, list_entities_summary

logger = get_logger("diagram")

_SKILL = load_skill("agents/diagram/SKILLS.md")

DIAGRAMS_DIR = os.path.join("workspace", "diagrams")


def _extract_json(raw: str) -> dict:
    start = raw.find("{")
    end = raw.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("No JSON object found in LLM response")
    return json.loads(raw[start:end + 1])


def _split_mermaid_blocks(content: str) -> list[Tuple[str, str]]:
    pattern = re.compile(
        r"^##\s+(?P<title>.+?)\s*\n+```mermaid\s*\n(?P<body>.*?)```",
        re.MULTILINE | re.DOTALL,
    )
    blocks: list[Tuple[str, str]] = []
    for m in pattern.finditer(content):
        title = m.group("title").strip()
        body = m.group("body").rstrip()
        blocks.append((title, body))
    return blocks


def _slug(title: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", title.strip().lower())
    return s.strip("_")


def _xml_escape(s: str) -> str:
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _drawio_wrapper(title: str, mermaid_body: str) -> str:
    """Wrap Mermaid as a drawio file with a single Mermaid shape.

    Draw.io supports embedded Mermaid via the `mxgraph.mermaid` shape
    starting around v20+. This produces an editable single-cell diagram
    that draw.io renders natively, and the source remains diff-friendly.
    """
    body_escaped = _xml_escape(mermaid_body)
    title_escaped = _xml_escape(title)
    return f"""<mxfile host="app.diagrams.net" type="device">
  <diagram name="{title_escaped}">
    <mxGraphModel dx="1200" dy="800" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1169" pageHeight="826" math="0" shadow="0">
      <root>
        <mxCell id="0" />
        <mxCell id="1" parent="0" />
        <mxCell id="mermaid-1" value="{body_escaped}" style="shape=mxgraph.mermaid;html=1;whiteSpace=wrap;fillColor=none;strokeColor=none;" vertex="1" parent="1">
          <mxGeometry x="40" y="40" width="1080" height="720" as="geometry" />
        </mxCell>
      </root>
    </mxGraphModel>
  </diagram>
</mxfile>
"""


def _write_mmd_and_drawio(category: str, mmd_content: str, out_dir: str) -> list[str]:
    """Persist the category .mmd plus per-block .drawio shards. Returns paths written."""
    written: list[str] = []
    if not mmd_content.strip():
        return written

    os.makedirs(out_dir, exist_ok=True)

    mmd_path = os.path.join(out_dir, f"{category}.mmd")
    with open(mmd_path, "w", encoding="utf-8") as f:
        f.write(mmd_content.rstrip() + "\n")
    written.append(mmd_path)

    blocks = _split_mermaid_blocks(mmd_content)
    if not blocks:
        logger.warning(f"No Mermaid blocks found in {category} — skipping drawio shards")
        return written

    shard_dir = os.path.join(out_dir, category)
    os.makedirs(shard_dir, exist_ok=True)
    for idx, (title, body) in enumerate(blocks, start=1):
        slug = _slug(title) or f"{category}_{idx}"
        drawio_path = os.path.join(shard_dir, f"{idx:02d}_{slug}.drawio")
        with open(drawio_path, "w", encoding="utf-8") as f:
            f.write(_drawio_wrapper(title, body))
        written.append(drawio_path)

    return written


def _embed_into_srs(srs_path: str, state_mmd: str, flows_mmd: str, sequences_mmd: str) -> None:
    """Inject a Diagrams appendix into the SRS file (idempotent: replaces existing block)."""
    if not os.path.exists(srs_path):
        logger.warning(f"SRS file {srs_path} not found — skipping embed")
        return

    with open(srs_path, "r", encoding="utf-8") as f:
        srs = f.read()

    marker_start = "<!-- DIAGRAMS_START -->"
    marker_end = "<!-- DIAGRAMS_END -->"

    block = (
        f"\n{marker_start}\n"
        "## Appendix F — Visual Diagrams\n\n"
        "Auto-generated by the Diagram Agent. Edit Mermaid sources in `workspace/diagrams/`.\n\n"
        "### F.1 State Machines\n\n"
        f"{state_mmd.strip()}\n\n"
        "### F.2 Business Flows\n\n"
        f"{flows_mmd.strip()}\n\n"
        "### F.3 System Sequences\n\n"
        f"{sequences_mmd.strip()}\n"
        f"{marker_end}\n"
    )

    if marker_start in srs and marker_end in srs:
        new_srs = re.sub(
            re.escape(marker_start) + r".*?" + re.escape(marker_end),
            block.strip(),
            srs,
            flags=re.DOTALL,
        )
    else:
        new_srs = srs.rstrip() + "\n" + block

    with open(srs_path, "w", encoding="utf-8") as f:
        f.write(new_srs)


def run(state):
    srs_content = state.get("srs", "")
    srs_path = state.get("srs_path") or os.path.join("workspace", "current_srs.md")

    if srs_path and os.path.exists(srs_path):
        with open(srs_path, "r", encoding="utf-8") as f:
            srs_content = f.read()

    if not srs_content.strip():
        logger.warning("No SRS content to diagram — skipping")
        export_agent_output(
            "diagram",
            output={"paths": [], "coverage": {}, "skipped": True},
            metadata={
                "iteration": state.get("iterations", 0),
                "reason": "no_srs_content",
            },
        )
        return state

    logger.info("Generating diagrams from SRS...")

    # Inject canonical entity & state names from the knowledge graph so the
    # diagram's stateDiagram-v2 blocks copy verbatim from the same source as
    # SRS §6 (avoids state-name drift between SRS and diagrams).
    graph_obj = load_graph()
    kg_block = ""
    if graph_obj is not None:
        index = list_entities_summary(graph_obj)
        stateful = [e for e in index if e.get("states")]
        if stateful:
            kg_block = (
                "\n\n## CANONICAL NAMES (copy verbatim — do not paraphrase)\n"
                + json.dumps(stateful, ensure_ascii=False, indent=2)
            )

    user = {"cached": f"SRS:\n{srs_content}", "suffix": kg_block}
    raw = call_llm(user, system=_SKILL)

    try:
        data = _extract_json(raw)
    except Exception as e:
        logger.error(f"Failed to parse diagram JSON: {e}")
        export_agent_output(
            "diagram",
            output={"paths": [], "coverage": {}, "parse_error": str(e)},
            metadata={
                "iteration": state.get("iterations", 0),
                "reason": "json_parse_failed",
            },
        )
        return state

    state_mmd = data.get("state_machines_mmd", "")
    flows_mmd = data.get("flows_mmd", "")
    sequences_mmd = data.get("sequences_mmd", "")
    coverage = data.get("coverage_report", {})

    out_dir = os.path.abspath(DIAGRAMS_DIR)
    os.makedirs(out_dir, exist_ok=True)

    written = []
    written += _write_mmd_and_drawio("state_machines", state_mmd, out_dir)
    written += _write_mmd_and_drawio("flows", flows_mmd, out_dir)
    written += _write_mmd_and_drawio("sequences", sequences_mmd, out_dir)

    coverage_path = os.path.join(out_dir, "coverage.json")
    with open(coverage_path, "w", encoding="utf-8") as f:
        json.dump(coverage, f, indent=2, ensure_ascii=False)
    written.append(coverage_path)

    logger.info(
        f"Diagram coverage — entities={len(coverage.get('entities_with_state_diagrams', []))} "
        f"flows={coverage.get('flows_count', 0)} sequences={coverage.get('sequences_count', 0)}"
    )
    logger.info(f"Wrote {len(written)} diagram artifacts to {out_dir}")

    _embed_into_srs(srs_path, state_mmd, flows_mmd, sequences_mmd)
    logger.info(f"Embedded diagrams into {srs_path}")

    export_agent_output(
        "diagram",
        output={
            "paths": written,
            "coverage": coverage,
        },
        metadata={
            "iteration": state.get("iterations", 0),
            "entities_with_state_diagrams": coverage.get("entities_with_state_diagrams", []),
            "flows_count": coverage.get("flows_count", 0),
            "sequences_count": coverage.get("sequences_count", 0),
            "artifact_count": len(written),
        },
    )

    return {
        **state,
        "diagram_paths": written,
        "diagram_coverage": coverage,
    }
